name: Node.js CI

on:
  push:
    tags:
      - v*
jobs:
  build-lin:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt install libssl-dev
      - run: sudo apt install libevent-dev
      - run: wget -O tor.tar.gz "https://dist.torproject.org/tor-0.4.4.6.tar.gz"
      - run: mkdir tor && tar -xvzf tor.tar.gz -C tor --strip-components=1
      - run: cd tor && ./configure && make
      - run: mkdir -p ./resources/lin/tor && mv ./tor/src/app/* ./resources/lin/tor
      - run: ls ./resources/lin/tor
      - run: npm install
      - run: npm run build-linux --if-present
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}